LINK = 'https://www.kinopoisk.ru/top/lists/221/'
NAME = 'Лауреаты премии золотой леопард'

MOVIES = [{'name': 'Девушка из ниоткуда',
  'country': ['Франция'],
  'budget': '€62000',
  'fees': {},
  'kinopoisk_rating': '5.844',
  'imdb_rating': '6.20',
  'id': '696765'},
 {'name': 'Откройте двери и окна',
  'country': ['Аргентина', 'Швейцария', 'Нидерланды'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '5.773',
  'imdb_rating': '6.10',
  'id': '606194'},
 {'name': 'Зимние каникулы',
  'country': ['Китай'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '5.855',
  'imdb_rating': '6.90',
  'id': '542566'},
 {'name': 'Она, китаянка',
  'country': ['Великобритания', 'Франция', 'Германия', 'Китай'],
  'budget': '0',
  'fees': {'сборы в России': 'сборы'},
  'kinopoisk_rating': '5.879',
  'imdb_rating': '6.00',
  'id': '450567'},
 {'name': 'В одиночестве',
  'country': ['Мексика'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '5.909',
  'imdb_rating': '6.70',
  'id': '436290'},
 {'name': 'Возрождение',
  'country': ['Япония'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '5.583',
  'imdb_rating': '6.20',
  'id': '395086'},
 {'name': 'Девушка',
  'country': ['Швейцария', 'Германия', 'Босния и Герцеговина'],
  'budget': '0',
  'fees': {'сборы в США': '$5715'},
  'kinopoisk_rating': '0',
  'imdb_rating': '6.80',
  'id': '197557'},
 {'name': 'Девять жизней',
  'country': ['США'],
  'budget': '$500000',
  'fees': {'сборы в США': '$478830', 'сборы в мире': '+$215736=$694566'},
  'kinopoisk_rating': '6.573',
  'imdb_rating': '6.80',
  'id': '81666'},
 {'name': 'Личное',
  'country': ['Италия'],
  'budget': '0',
  'fees': {'сборы в США': '$15811', 'сборы в мире': '+$9579866=$9595677'},
  'kinopoisk_rating': '0',
  'imdb_rating': '7.00',
  'id': '91417'},
 {'name': 'Тихие воды',
  'country': ['Пакистан', 'Франция', 'Германия'],
  'budget': '0',
  'fees': {'сборы в США': '$7384'},
  'kinopoisk_rating': '0',
  'imdb_rating': '7.60',
  'id': '51216'},
 {'name': 'Желание',
  'country': ['Германия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '6.40',
  'id': '116628'},
 {'name': 'В революцию на двух лошадях',
  'country': ['Италия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '6.20',
  'id': '39781'},
 {'name': 'Отец',
  'country': ['Китай'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '7.20',
  'id': '213330'},
 {'name': 'Шкура человека, сердце зверя',
  'country': ['Франция'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '5.463',
  'imdb_rating': '6.40',
  'id': '61178'},
 {'name': 'Господин Чжао',
  'country': ['Гонконг', 'Китай'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '7.10',
  'id': '173854'},
 {'name': 'Зеркало',
  'country': ['Иран'],
  'budget': '0',
  'fees': {'сборы в США': '$44970'},
  'kinopoisk_rating': '5.927',
  'imdb_rating': '7.60',
  'id': '250974'},
 {'name': 'Ненетт и Бони',
  'country': ['Франция'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '6.598',
  'imdb_rating': '7.00',
  'id': '11061'},
 {'name': 'Спица',
  'country': ['Франция'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '5.10',
  'id': '54018'},
 {'name': 'Кувшин',
  'country': ['Иран'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '7.20',
  'id': '244579'},
 {'name': 'Место на серой треуголке',
  'country': ['Казахстан'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '5.373',
  'imdb_rating': '6.20',
  'id': '253582'},
 {'name': 'Осенняя луна',
  'country': ['Гонконг', 'Япония'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '7.10',
  'id': '59957'},
 {'name': 'Джонни-замша',
  'country': ['Швейцария', 'Франция', 'США'],
  'budget': '$500000',
  'fees': {'сборы в США': '$90091'},
  'kinopoisk_rating': '5.890',
  'imdb_rating': '5.80',
  'id': '9536'},
 {'name': 'Случайный вальс',
  'country': ['СССР'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '5.608',
  'imdb_rating': '5.40',
  'id': '43862'},
 {'name': 'Почему Бодхидхарма ушел на Восток?',
  'country': ['Корея Южная'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '6.960',
  'imdb_rating': '7.70',
  'id': '394406'},
 {'name': 'Бабочка',
  'country': ['Германия (ФРГ)'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '7.60',
  'id': '92519'},
 {'name': 'Далекие голоса, застывшие жизни',
  'country': ['Великобритания', 'Германия (ФРГ)'],
  'budget': '0',
  'fees': {'сборы в США': '$688329'},
  'kinopoisk_rating': '6.810',
  'imdb_rating': '7.50',
  'id': '9379'},
 {'name': 'Шут',
  'country': ['Португалия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '5.881',
  'imdb_rating': '6.90',
  'id': '61558'},
 {'name': 'Боденское озеро',
  'country': ['Польша'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '5.80',
  'id': '66117'},
 {'name': 'Горные огни',
  'country': ['Швейцария'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '6.771',
  'imdb_rating': '7.10',
  'id': '139657'},
 {'name': 'Более странно, чем в раю',
  'country': ['США', 'Германия (ФРГ)'],
  'budget': '$90000',
  'fees': {'сборы в США': '$2436000'},
  'kinopoisk_rating': '7.724',
  'imdb_rating': '7.60',
  'id': '17705'},
 {'name': 'Дай, король, солдата',
  'country': ['Венгрия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '8.00',
  'id': '75908'},
 {'name': 'Исход',
  'country': ['Индия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '7.10',
  'id': '171799'},
 {'name': 'Проклятые, я вас люблю',
  'country': ['Италия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '7.00',
  'id': '198996'},
 {'name': 'Стадо',
  'country': ['Турция'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '6.105',
  'imdb_rating': '8.40',
  'id': '71020'},
 {'name': 'Лентяи плодородной долины',
  'country': ['Греция'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '6.435',
  'imdb_rating': '7.30',
  'id': '147588'},
 {'name': 'Антонио Грамши: Тюремные дни',
  'country': ['Италия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '6.20',
  'id': '133472'},
 {'name': 'Большая ночь',
  'country': ['Швейцария'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '6.50',
  'id': '126863'},
 {'name': 'Сын Амра мёртв',
  'country': ['Бельгия', 'Франция', 'Тунис'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '6.50',
  'id': '124611'},
 {'name': 'Улица Тюзолто, 25',
  'country': ['Венгрия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '6.495',
  'imdb_rating': '6.60',
  'id': '36161'},
 {'name': 'Иллюминация',
  'country': ['Польша'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '7.687',
  'imdb_rating': '7.30',
  'id': '68277'},
 {'name': 'Мрачные моменты',
  'country': ['Великобритания'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '6.840',
  'imdb_rating': '7.70',
  'id': '35601'},
 {'name': 'Дорожные знаки',
  'country': ['Польша'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '6.40',
  'id': '225273'},
 {'name': 'Частная дорога',
  'country': ['Великобритания'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '6.30',
  'id': '185702'},
 {'name': 'Друзья',
  'country': ['Франция'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '7.40',
  'id': '100950'},
 {'name': 'В момент смерти',
  'country': ['Италия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '0',
  'id': '581085'},
 {'name': 'Конец дороги',
  'country': ['США'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '6.60',
  'id': '2827'},
 {'name': 'О, солнце',
  'country': ['Франция', 'Мавритания'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '7.20',
  'id': '272606'},
 {'name': 'Бренность',
  'country': ['Япония'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '7.222',
  'imdb_rating': '8.20',
  'id': '383132'},
 {'name': 'Лилика',
  'country': ['Югославия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '6.90',
  'id': '123648'},
 {'name': 'В огне брода нет',
  'country': ['СССР'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '7.795',
  'imdb_rating': '7.60',
  'id': '45621'},
 {'name': 'Три грустных тигра',
  'country': ['Чили'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '5.593',
  'imdb_rating': '7.10',
  'id': '57889'},
 {'name': 'Очкарики',
  'country': ['Венгрия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '5.90',
  'id': '75571'},
 {'name': 'Шарль мертв или жив',
  'country': ['Швейцария'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '7.142',
  'imdb_rating': '7.30',
  'id': '126866'},
 {'name': 'Экстравагантные',
  'country': ['Италия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '0',
  'id': '175477'},
 {'name': 'Земля в трансе',
  'country': ['Бразилия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '6.390',
  'imdb_rating': '7.50',
  'id': '37987'},
 {'name': 'Отвага на каждый день',
  'country': ['Чехословакия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '6.234',
  'imdb_rating': '6.60',
  'id': '49086'},
 {'name': 'Утром вчетвером',
  'country': ['Великобритания'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '6.60',
  'id': '19028'},
 {'name': 'Черный Петр',
  'country': ['Чехословакия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '7.348',
  'imdb_rating': '7.20',
  'id': '14973'},
 {'name': 'Эшелон из рая',
  'country': ['Чехословакия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '7.20',
  'id': '51074'},
 {'name': 'Щедрое сердце',
  'country': ['Франция'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '5.040',
  'imdb_rating': '6.60',
  'id': '362666'},
 {'name': 'Полевые огни',
  'country': ['Япония'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '7.647',
  'imdb_rating': '8.00',
  'id': '143955'},
 {'name': 'Красавчик Антонио',
  'country': ['Италия', 'Франция'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '7.133',
  'imdb_rating': '7.50',
  'id': '13541'},
 {'name': 'Поцелуй убийцы',
  'country': ['США'],
  'budget': '$75000',
  'fees': {},
  'kinopoisk_rating': '6.657',
  'imdb_rating': '6.70',
  'id': '9694'},
 {'name': 'Дом №10 по Северной улице Фредерик',
  'country': ['США'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '7.00',
  'id': '3335'},
 {'name': 'Крик',
  'country': ['Италия', 'США'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '7.594',
  'imdb_rating': '7.80',
  'id': '63931'},
 {'name': 'Соловей Императора',
  'country': ['Чехословакия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '5.738',
  'imdb_rating': '6.90',
  'id': '32161'},
 {'name': 'Кармен Джонс',
  'country': ['США'],
  'budget': '$750000',
  'fees': {},
  'kinopoisk_rating': '5.764',
  'imdb_rating': '6.90',
  'id': '25387'},
 {'name': 'Такие разные судьбы',
  'country': ['Франция'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '7.021',
  'imdb_rating': '6.90',
  'id': '159130'},
 {'name': 'Ротация',
  'country': ['Германия (ГДР)'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '7.40',
  'id': '72796'},
 {'name': 'Дикие фрукты',
  'country': ['Франция'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '6.60',
  'id': '179121'},
 {'name': 'Врата ада',
  'country': ['Япония'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '7.245',
  'imdb_rating': '7.20',
  'id': '7726'},
 {'name': 'Принц Баяя',
  'country': ['Чехословакия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '7.10',
  'id': '183434'},
 {'name': 'Стеклянная стена',
  'country': ['США'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '6.90',
  'id': '10769'},
 {'name': 'Композитор Глинка',
  'country': ['СССР'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '6.336',
  'imdb_rating': '7.00',
  'id': '44883'},
 {'name': 'Юлий Цезарь',
  'country': ['США'],
  'budget': '$2070000',
  'fees': {'сборы в США': '$2021000'},
  'kinopoisk_rating': '7.561',
  'imdb_rating': '7.40',
  'id': '7165'},
 {'name': 'Преследуемый',
  'country': ['Великобритания'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '6.223',
  'imdb_rating': '7.50',
  'id': '36346'},
 {'name': 'Когда Вилли возвращался домой',
  'country': ['США'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '5.392',
  'imdb_rating': '6.60',
  'id': '1140'},
 {'name': 'Ферма семи грехов',
  'country': ['Франция'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '0',
  'imdb_rating': '6.90',
  'id': '263129'},
 {'name': 'Германия, год нулевой',
  'country': ['Италия', 'Франция', 'Германия'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '7.978',
  'imdb_rating': '7.90',
  'id': '57082'},
 {'name': 'Молчание – золото',
  'country': ['Франция', 'США'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '7.155',
  'imdb_rating': '7.30',
  'id': '26629'},
 {'name': 'И не осталось никого',
  'country': ['США'],
  'budget': '0',
  'fees': {},
  'kinopoisk_rating': '7.038',
  'imdb_rating': '7.60',
  'id': '8345'}]

